---
version: 0.2

branches:
  default:
    stage: pre-merge

stages:
  pre-merge:
    worker: &master-worker
      type: docker
      path: eve/workers/master
      volumes:
        - '/home/eve/workspace'
    steps:
      - Git:
          name: fetch source
          repourl: '%(prop:git_reference)s'
          shallow: True
          retryFetch: True
          haltOnFailure: True
      - ShellCommand:
          name: install dependencies
          command: npm install
      - ShellCommand:
          name: run lint
          command: npm run --silent lint -- --max-warnings 0
      - ShellCommand:
          name: set host bucketclient.testing.local 
          command: sudo bash -c 'echo "127.0.0.1 bucketclient.testing.local" >> /etc/hosts'
      - ShellCommand:
          name: run test
          command: npm run --silent test
