name: tests

on:
  push:
    branches-ignore:
      - 'development/**'

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Update yarn
        run: corepack enable && yarn set version stable
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        run: yarn install --immutable
      - name: run lint
        run: yarn run --silent lint -- --max-warnings 0
      - name: set host bucketclient.testing.local
        run: sudo bash -c 'echo "127.0.0.1 bucketclient.testing.local" >> /etc/hosts'
      - name: run test
        run: yarn run --silent test
