name: tests

on:
  push:
    branches-ignore:
      - 'development/**'

jobs:
  tests:
    runs-on: [self-hosted, ubuntu, focal, large]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '10'
      - name: install yarn
        run: |
          curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
          echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
          sudo apt update && sudo apt install yarn build-essential -y
      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
      - name: install dependencies
        run: yarn install --frozen-lockfile
      - name: run lint
        run: yarn run --silent lint -- --max-warnings 0
      - name: set host bucketclient.testing.local
        run: sudo bash -c 'echo "127.0.0.1 bucketclient.testing.local" >> /etc/hosts'
      - name: run test
        run: yarn run --silent test
